name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    # ✅ Install Docker + Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # ✅ Now run your container & test monitoring
    - name: Test Monitoring Endpoint
      run: |
        docker-compose up -d
        sleep 20

    - name: Show Docker logs
      run: docker-compose logs

    - name: Curl Monitoring Endpoint
      run: curl -f http://localhost:8000/metrics

